### ISSUE TITLE
Change quickstarts to use `extism generate`

### ISSUE THREAD

**Issue by bhelx** [extism/cli#83]
Let's change all the quickstarts to use extism generate: https://extism.org/docs/quickstart/plugin-quickstart
It'll make them shorter and make sure they are always working and up to date.

**Comment by bhelx** [comment]
Open to interpretation on how to apply this. I also think that we should look at changing the pdk readmes as well where it makes sense.

**Comment by neuronicnobody** [comment]
Note, there is already a call out at the top of the Quickstarts pointing users to Extism generate instructions.

**Comment by bhelx** [comment]
yeah but instead of a note calling it out as an option, we should change the instructions. as stated:

> It'll make them shorter and make sure they are always working and up to date.
